
# parsetab_astmatch.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '8770632605DBD8511D3EC8B9BC5D91A8'
    
_lr_action_items = {'CODE':([0,1,3,4,5,6,7,8,10,11,12,13,15,16,17,18,19,],[-13,4,-9,-7,4,-13,-13,-13,-8,-12,4,4,4,-6,-13,-2,4,]),'STAR':([0,1,3,4,5,6,7,8,10,11,12,13,15,16,17,18,19,],[-13,-13,-9,-7,11,-13,-13,-13,-8,-12,-11,-13,-10,-6,-13,-2,-13,]),'RBK':([3,4,6,7,8,10,11,12,13,14,15,16,17,18,19,],[-9,-7,-13,-5,-13,-8,-12,-11,-3,18,-10,-6,-13,-2,-4,]),'WORD':([9,],[16,]),'NOT':([0,1,3,4,5,6,7,8,10,11,12,13,15,16,17,18,19,],[-13,6,-9,-7,6,-13,-13,-13,-8,-12,6,6,6,-6,-13,-2,6,]),'COMMA':([3,4,6,7,8,10,11,12,13,14,15,16,17,18,19,],[-9,-7,-13,-5,-13,-8,-12,-11,-3,17,-10,-6,-13,-2,-4,]),'LBK':([0,1,3,4,5,6,7,8,10,11,12,13,15,16,17,18,19,],[-13,7,-9,-7,7,-13,-13,-13,-8,-12,7,7,7,-6,-13,-2,7,]),'OR':([0,1,3,4,5,6,7,8,10,11,12,13,15,16,17,18,19,],[-13,8,-9,-7,8,-13,-13,-13,-8,-12,8,8,8,-6,-13,-2,8,]),'SPECIAL':([0,1,3,4,5,6,7,8,10,11,12,13,15,16,17,18,19,],[-13,9,-9,-7,9,-13,-13,-13,-8,-12,9,9,9,-6,-13,-2,9,]),'$end':([0,1,2,3,4,6,8,10,11,12,15,16,18,],[-13,-1,0,-9,-7,-13,-13,-8,-12,-11,-10,-6,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ast_set':([1,5,12,13,15,19,],[3,3,3,3,3,3,]),'ast_special':([1,5,12,13,15,19,],[10,10,10,10,10,10,]),'ast_exprlist':([7,],[14,]),'ast_expr':([0,1,5,6,7,8,12,13,15,17,19,],[1,5,5,12,13,15,5,5,5,19,5,]),'ast_match':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ast_match","S'",1,None,None,None),
  ('ast_match -> ast_expr','ast_match',1,'p_ast_match','js_ast_match.py',46),
  ('ast_set -> LBK ast_exprlist RBK','ast_set',3,'p_ast_set','js_ast_match.py',52),
  ('ast_exprlist -> ast_expr','ast_exprlist',1,'p_ast_exprlist','js_ast_match.py',60),
  ('ast_exprlist -> ast_exprlist COMMA ast_expr','ast_exprlist',3,'p_ast_exprlist','js_ast_match.py',61),
  ('ast_exprlist -> <empty>','ast_exprlist',0,'p_ast_exprlist','js_ast_match.py',62),
  ('ast_special -> SPECIAL WORD','ast_special',2,'p_ast_noderef','js_ast_match.py',76),
  ('ast_expr -> ast_expr CODE','ast_expr',2,'p_ast_expr','js_ast_match.py',82),
  ('ast_expr -> ast_expr ast_special','ast_expr',2,'p_ast_expr','js_ast_match.py',83),
  ('ast_expr -> ast_expr ast_set','ast_expr',2,'p_ast_expr','js_ast_match.py',84),
  ('ast_expr -> ast_expr OR ast_expr','ast_expr',3,'p_ast_expr','js_ast_match.py',85),
  ('ast_expr -> ast_expr NOT ast_expr','ast_expr',3,'p_ast_expr','js_ast_match.py',86),
  ('ast_expr -> ast_expr ast_expr STAR','ast_expr',3,'p_ast_expr','js_ast_match.py',87),
  ('ast_expr -> <empty>','ast_expr',0,'p_ast_expr','js_ast_match.py',88),
]
