
# parsetab_re.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'E3F71B5E13CD4163FAAA6EEF88916462'
    
_lr_action_items = {'ID_PART':([2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,],[12,-4,-19,-5,14,-33,-20,-6,-7,-21,27,-18,-15,-16,-11,-12,-17,-13,-14,35,-37,-24,-3,-22,-25,-8,-23,-9,-10,-28,-29,-27,-30,-34,-26,-31,-35,-32,42,-36,]),'STAR':([3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,19,20,21,22,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,],[-4,-19,-5,15,-33,-20,-6,-7,-21,24,-18,-15,-16,-11,-12,-17,-13,-14,32,-24,-3,-22,-25,-8,-23,-9,-10,-28,-29,-27,-30,-34,-26,-31,-35,-32,]),'DIVIDE':([0,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,],[2,-4,-19,-5,16,-33,-20,-6,23,-7,-21,-2,-18,-15,-16,-11,-12,-17,-13,-14,33,-24,-3,-22,-25,-8,-23,-9,-10,-28,-29,-27,-30,-34,-26,-31,-35,-32,]),'UCHAR':([2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,19,20,21,22,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,],[4,-4,-19,-5,18,-33,-20,-6,-7,-21,26,-18,-15,-16,-11,-12,-17,-13,-14,37,-24,-3,-22,-25,-8,-23,-9,-10,-28,-29,-27,-30,-34,-26,-31,-35,-32,]),'BACKSLASH':([2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,19,20,21,22,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,],[6,-4,-19,-5,19,-33,-20,-6,-7,-21,6,-18,-15,-16,-11,-12,-17,-13,-14,6,-24,-3,-22,-25,-8,-23,-9,-10,-28,-29,-27,-30,-34,-26,-31,-35,-32,]),'LSBRACKET':([2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,19,20,21,22,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,],[7,-4,-19,-5,20,-33,-20,-6,-7,-21,7,-18,-15,-16,-11,-12,-17,-13,-14,34,-24,-3,-22,-25,-8,-23,-9,-10,-28,-29,-27,-30,-34,-26,-31,-35,-32,]),'RSBRACKET':([2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,19,20,21,22,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,],[8,-4,-19,-5,21,-33,-20,-6,-7,-21,29,-18,-15,-16,-11,-12,-17,-13,-14,38,-24,-3,-22,-25,-8,-23,-9,-10,-28,-29,-27,-30,-34,-26,-31,-35,-32,]),'$end':([1,23,41,42,],[0,-37,-1,-36,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'re_first_char':([2,],[3,]),'re_char':([13,],[25,]),'re_non_term':([6,],[17,]),'re_class_chars':([7,],[22,]),'re_lit':([0,],[1,]),'re_non_term_restrict1':([2,],[5,]),'re_non_term_restrict2':([13,],[28,]),'re_non_term_restrict3':([22,],[36,]),'re_backlash_seq':([2,13,22,],[9,30,39,]),'re_body':([2,],[10,]),'re_expr_class':([2,13,],[11,31,]),'re_class_char':([22,],[40,]),'re_flags':([23,],[41,]),'re_chars':([3,],[13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> re_lit","S'",1,None,None,None),
  ('re_lit -> DIVIDE re_body DIVIDE re_flags','re_lit',4,'p_re_lit','js_regexpr_parse.py',51),
  ('re_body -> re_first_char re_chars','re_body',2,'p_re_body','js_regexpr_parse.py',56),
  ('re_chars -> re_chars re_char','re_chars',2,'p_re_chars','js_regexpr_parse.py',61),
  ('re_chars -> <empty>','re_chars',0,'p_re_chars','js_regexpr_parse.py',62),
  ('re_first_char -> re_non_term_restrict1','re_first_char',1,'p_re_first_char','js_regexpr_parse.py',71),
  ('re_first_char -> re_backlash_seq','re_first_char',1,'p_re_first_char','js_regexpr_parse.py',72),
  ('re_first_char -> re_expr_class','re_first_char',1,'p_re_first_char','js_regexpr_parse.py',73),
  ('re_char -> re_non_term_restrict2','re_char',1,'p_re_char','js_regexpr_parse.py',79),
  ('re_char -> re_backlash_seq','re_char',1,'p_re_char','js_regexpr_parse.py',80),
  ('re_char -> re_expr_class','re_char',1,'p_re_char','js_regexpr_parse.py',81),
  ('re_backlash_seq -> BACKSLASH re_non_term','re_backlash_seq',2,'p_re_backlash_seq','js_regexpr_parse.py',87),
  ('re_non_term -> UCHAR','re_non_term',1,'p_re_non_term','js_regexpr_parse.py',92),
  ('re_non_term -> LSBRACKET','re_non_term',1,'p_re_non_term','js_regexpr_parse.py',93),
  ('re_non_term -> RSBRACKET','re_non_term',1,'p_re_non_term','js_regexpr_parse.py',94),
  ('re_non_term -> STAR','re_non_term',1,'p_re_non_term','js_regexpr_parse.py',95),
  ('re_non_term -> DIVIDE','re_non_term',1,'p_re_non_term','js_regexpr_parse.py',96),
  ('re_non_term -> BACKSLASH','re_non_term',1,'p_re_non_term','js_regexpr_parse.py',97),
  ('re_non_term -> ID_PART','re_non_term',1,'p_re_non_term','js_regexpr_parse.py',98),
  ('re_non_term_restrict1 -> UCHAR','re_non_term_restrict1',1,'p_re_non_term_restrict1','js_regexpr_parse.py',103),
  ('re_non_term_restrict1 -> RSBRACKET','re_non_term_restrict1',1,'p_re_non_term_restrict1','js_regexpr_parse.py',104),
  ('re_non_term_restrict1 -> ID_PART','re_non_term_restrict1',1,'p_re_non_term_restrict1','js_regexpr_parse.py',105),
  ('re_non_term_restrict2 -> UCHAR','re_non_term_restrict2',1,'p_re_non_term_restrict2','js_regexpr_parse.py',110),
  ('re_non_term_restrict2 -> RSBRACKET','re_non_term_restrict2',1,'p_re_non_term_restrict2','js_regexpr_parse.py',111),
  ('re_non_term_restrict2 -> STAR','re_non_term_restrict2',1,'p_re_non_term_restrict2','js_regexpr_parse.py',112),
  ('re_non_term_restrict2 -> ID_PART','re_non_term_restrict2',1,'p_re_non_term_restrict2','js_regexpr_parse.py',113),
  ('re_non_term_restrict3 -> UCHAR','re_non_term_restrict3',1,'p_re_non_term_restrict3','js_regexpr_parse.py',119),
  ('re_non_term_restrict3 -> LSBRACKET','re_non_term_restrict3',1,'p_re_non_term_restrict3','js_regexpr_parse.py',120),
  ('re_non_term_restrict3 -> STAR','re_non_term_restrict3',1,'p_re_non_term_restrict3','js_regexpr_parse.py',121),
  ('re_non_term_restrict3 -> DIVIDE','re_non_term_restrict3',1,'p_re_non_term_restrict3','js_regexpr_parse.py',122),
  ('re_non_term_restrict3 -> ID_PART','re_non_term_restrict3',1,'p_re_non_term_restrict3','js_regexpr_parse.py',123),
  ('re_expr_class -> LSBRACKET re_class_chars RSBRACKET','re_expr_class',3,'p_re_expr_class','js_regexpr_parse.py',128),
  ('re_class_chars -> re_class_chars re_class_char','re_class_chars',2,'p_re_class_chars','js_regexpr_parse.py',134),
  ('re_class_chars -> <empty>','re_class_chars',0,'p_re_class_chars','js_regexpr_parse.py',135),
  ('re_class_char -> re_non_term_restrict3','re_class_char',1,'p_re_class_char','js_regexpr_parse.py',144),
  ('re_class_char -> re_backlash_seq','re_class_char',1,'p_re_class_char','js_regexpr_parse.py',145),
  ('re_flags -> re_flags ID_PART','re_flags',2,'p_re_flags','js_regexpr_parse.py',151),
  ('re_flags -> <empty>','re_flags',0,'p_re_flags','js_regexpr_parse.py',152),
]
